### PR TITLE
Release v.0.0.5

### PR DESCRIPTION
**Pull request by ignasiusadhitia**
### Release
---
- [fix: change static id](https://github.com/ignasiusadhitia/final-project-dash/pull/31)

### CODE REVIEW

**Comment by ignasiusadhitia** [comment]
https://exclusive-store-dash-git-development-ignasiusadhitias-projects.vercel.app/?_vercel_share=cgZrZGau4d3eMRPabWZjXEzhrOTscoVn

**Review by rikkriuk — APPROVED** [review]
All feature work so well

**Comment by ignasiusadhitia** [comment]
https://exclusive-store-dash-git-development-ignasiusadhitias-projects.vercel.app/?_vercel_share=cgZrZGau4d3eMRPabWZjXEzhrOTscoVn

**Review by desup1421 — APPROVED** [review]
Excellent! 🚀🚀🚀

**Review by dvpms — COMMENTED** [review]
Everything is done

**Pull request merged**
